const { google } = require("googleapis");

const sendMsgReply = async (auth, threadId, msgDetails) => {
  try {
    const emailContent = `To:${msgDetails.sendTo}\nSubject:${msgDetails.subject}\n\nHey, This is an autogenerated email as I am on a vacation. Give me a call if it is urgent.`;
    const base64string = Buffer.from(emailContent).toString("base64");
    const gmail = google.gmail({ version: "v1", auth });
    const mail = await gmail.users.messages.send({
      userId: "me",
      resource: {
        payload: {
          headers: [
            { name: "To", value: `${msgDetails.sendTo}` },
            // { name: "From", value: "first last <somepersonsemail@gmail.com>" },
            // { name: "Subject", value: "Saying Hello" },
          ],
        },
        raw: base64string,
        threadId: threadId,
      },
    });
    // console.log(mail);
    return mail;
  } catch (error) {
    console.log(error);
  }
};

module.exports = sendMsgReply;
